packages:
  - apps/*
  - examples/*
  - packages/*
  - shared/*

catalog:
  "@types/node": ^25.6.0
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.19

onlyBuiltDependencies:
  - esbuild
  - sharp
  - wasm-pack

overrides:
  esbuild: "^0.28.0"
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
