packages:
  - apps/*
  - examples/*
  - packages/*
  - shared/*

allowBuilds:
  esbuild: true
  sharp: true
  wasm-pack: true

catalog:
  "@types/node": ^25.7.0
  playwright: ^1.60.0
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest

overrides:
  esbuild: "^0.28.0"
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
