import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const outputPath = resolve(
  root,
  "tests/framework-whitespace/generated/MatrixHarness.astro",
);
const casesOutputPath = resolve(
  root,
  "tests/framework-whitespace/generated/cases.ts",
);

const nodeKinds = [
  "text",
  "inline",
  "interpolation",
  "ternary",
  "fragment",
  "set-text",
  "set-html",
  "nested",
] as const;
const gapKinds = ["sp", "nl"] as const;

type NodeKind = (typeof nodeKinds)[number];
type GapKind = (typeof gapKinds)[number];
type Label = "L" | "R";

function renderNode(kind: NodeKind, label: Label): string {
  switch (kind) {
    case "text":
      return label;
    case "inline":
      return `<span class="fixture-inline">${label}</span>`;
    case "interpolation":
      return `{${label === "L" ? "leftLabel" : "rightLabel"}}`;
    case "ternary":
      return `{true ? <span class="fixture-inline">${label}</span> : null}`;
    case "fragment":
      return `<Fragment><span class="fixture-inline">${label}</span></Fragment>`;
    case "set-text":
      return `<span class="fixture-inline-text" set:text={${label === "L" ? "leftLabel" : "rightLabel"}}></span>`;
    case "set-html":
      return `<span class="fixture-inline-host" set:html={${label === "L" ? "leftHtml" : "rightHtml"}}></span>`;
    case "nested":
      return `<div class="fixture-box"><strong class="fixture-strong">${label}</strong> tail</div>`;
  }
}

function renderGap(gap: GapKind): string {
  return gap === "sp" ? " " : "\n";
}

const cases: string[] = [];
const sections: string[] = [];

for (const leftKind of nodeKinds) {
  for (const gap of gapKinds) {
    for (const rightKind of nodeKinds) {
      const caseId = `pair-${leftKind}-${gap}-${rightKind}`;
      cases.push(caseId);
      sections.push(`  <whitespace-case data-case="${caseId}">
    ${renderNode(leftKind, "L")}${renderGap(gap)}${renderNode(rightKind, "R")}
  </whitespace-case>`);
    }
  }
}

const source = `---
const leftLabel = "L";
const rightLabel = "R";
const leftHtml = '<span class="fixture-inline-html">L</span>';
const rightHtml = '<span class="fixture-inline-html">R</span>';
---

<!-- Generated by scripts/generate-framework-whitespace-fixtures.ts -->
<section data-framework-whitespace-fixtures>
${sections.join("\n\n")}
</section>
`;

await mkdir(resolve(outputPath, ".."), { recursive: true });
await writeFile(outputPath, source, "utf8");
await writeFile(
  casesOutputPath,
  `export const frameworkWhitespaceCases = ${JSON.stringify(cases, null, 2)} as const;\n`,
  "utf8",
);
