import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const outputPath = resolve(
  root,
  "tests/framework-whitespace/generated/MatrixHarness.svelte",
);
const casesOutputPath = resolve(
  root,
  "tests/framework-whitespace/generated/cases.ts",
);

const nodeKinds = [
  "text",
  "inline",
  "interpolation",
  "html",
  "render",
  "nested",
] as const;
const gapKinds = ["sp", "nl"] as const;
const blockKinds = ["if", "each"] as const;

type NodeKind = (typeof nodeKinds)[number];
type GapKind = (typeof gapKinds)[number];
type BlockKind = (typeof blockKinds)[number];
type Label = "L" | "R";

function renderNode(kind: NodeKind, label: Label): string {
  switch (kind) {
    case "text":
      return label;
    case "inline":
      return `<span class="fixture-inline">${label}</span>`;
    case "interpolation":
      return `{${label === "L" ? "leftLabel" : "rightLabel"}}`;
    case "html":
      return `{@html ${label === "L" ? "leftHtml" : "rightHtml"}}`;
    case "render":
      return `{@render inlineSnippet(${label === "L" ? "leftLabel" : "rightLabel"})}`;
    case "nested":
      return `<div class="fixture-box"><strong class="fixture-strong">${label}</strong> tail</div>`;
  }
}

function renderGap(gap: GapKind): string {
  return gap === "sp" ? " " : "\n";
}

function renderBlockOpen(
  kind: BlockKind,
  gap: GapKind,
  rightKind: NodeKind,
): string {
  switch (kind) {
    case "if":
      return `{#if true}${renderGap(gap)}${renderNode(rightKind, "R")}{/if}`;
    case "each":
      return `{#each blockLabels as label}${renderGap(gap)}${renderNode(rightKind, "R")}{/each}`;
  }
}

function renderBlockClose(
  kind: BlockKind,
  leftKind: NodeKind,
  gap: GapKind,
): string {
  switch (kind) {
    case "if":
      return `{#if true}${renderNode(leftKind, "L")}${renderGap(gap)}{/if}`;
    case "each":
      return `{#each blockLabels as label}${renderNode(leftKind, "L")}${renderGap(gap)}{/each}`;
  }
}

const cases: string[] = [];
const sections: string[] = [];

for (const leftKind of nodeKinds) {
  for (const gap of gapKinds) {
    for (const rightKind of nodeKinds) {
      const caseId = `pair-${leftKind}-${gap}-${rightKind}`;
      cases.push(caseId);
      sections.push(`  <whitespace-case data-case="${caseId}">
    ${renderNode(leftKind, "L")}${renderGap(gap)}${renderNode(rightKind, "R")}
  </whitespace-case>`);
    }
  }
}

for (const blockKind of blockKinds) {
  for (const gap of gapKinds) {
    for (const rightKind of nodeKinds) {
      const caseId = `${blockKind}-open-${gap}-${rightKind}`;
      cases.push(caseId);
      sections.push(`  <whitespace-case data-case="${caseId}">
    ${renderBlockOpen(blockKind, gap, rightKind)}
  </whitespace-case>`);
    }
  }
}

for (const blockKind of blockKinds) {
  for (const leftKind of nodeKinds) {
    for (const gap of gapKinds) {
      const caseId = `${blockKind}-close-${leftKind}-${gap}`;
      cases.push(caseId);
      sections.push(`  <whitespace-case data-case="${caseId}">
    ${renderBlockClose(blockKind, leftKind, gap)}
  </whitespace-case>`);
    }
  }
}

const source = `<script lang="ts">
  const leftLabel = "L";
  const rightLabel = "R";
  const leftHtml = '<span class="fixture-inline-html">L</span>';
  const rightHtml = '<span class="fixture-inline-html">R</span>';
  const blockLabels = ["only"];
</script>

{#snippet inlineSnippet(label: string)}
  <span class="fixture-inline">{label}</span>
{/snippet}

<!-- Generated by scripts/generate-framework-whitespace-fixtures.ts -->
<section data-framework-whitespace-fixtures>
${sections.join("\n\n")}
</section>
`;

await mkdir(resolve(outputPath, ".."), { recursive: true });
await writeFile(outputPath, source, "utf8");
await writeFile(
  casesOutputPath,
  `export const frameworkWhitespaceCases = ${JSON.stringify(cases, null, 2)} as const;\n`,
  "utf8",
);
